version: '3.7' # Use a suitable version for your requirements

services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

  jenkins-blueocean:
    container_name: jenkins-blueocean
    image: myjenkins-blueocean:2.440.1
    restart: on-failure
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins:
    name: jenkins

volumes:
  jenkins-docker-certs:
    name: jenkins-docker-certs
  jenkins-data:
    name: jenkins-data

